version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    environment:
      SA_PASSWORD: "SignMeUp!1"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - /temp/db:/temp/db
